### ISSUE TITLE
Is esp32-smbus thread safe?

### ISSUE THREAD

**Issue by lukecyca** [DavidAntliff/esp32-smbus#2]
I am using [esp32-i2c-lcd1602](https://github.com/DavidAntliff/esp32-i2c-lcd1602) and [esp32-mcp342x](https://github.com/craftmetrics/esp32-mcp342x) on a single i2c bus and occasionally the LCD becomes corrupt. I have one task updating the LCD, and a different task polling the MCP342x.

Is it safe to use these simultaneously, or do I need to apply my own mutex to ensure they don't occur at the same time?

[This issue](https://github.com/espressif/esp-idf/issues/1997) suggests that at least some of the underlying I2C APIs are already protected by a mutex, but it's not very clear to what extent.

Thanks!

**Comment by DavidAntliff** [comment]
@lukecyca esp32-smbus makes use of the ESP-IDF I2C master component, which is not thread-safe between transactions as far as I understand. You probably have to protect access to the bus yourself. I do this at the top level in my own apps, for example: https://github.com/DavidAntliff/esp32-poolmon/blob/master/main/sensor_light.c#L104

**Comment by lukecyca** [comment]
Thanks! That is the answer I was hoping for.
